apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-core-api-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    app: core-api
    release: {{ .Release.Name }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: core-api

