{{- if (.Values.networkPolicy | default dict).enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-egress-openai-via-squid
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      egress: openai-via-squid
  policyTypes: ["Egress"]
  egress:
    - to:
        - ipBlock:
            cidr: 109.120.129.63/32
      ports:
        - protocol: TCP
          port: 48011
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - namespaceSelector: {}
          podSelector: {}
{{- end }}
