{{- $secrets := .Values.secrets | default (dict) -}}
{{- $useExternal := and (hasKey $secrets "useExternal") $secrets.useExternal -}}
{{- $useExisting := and (hasKey $secrets "useExisting") $secrets.useExisting -}}

{{- if not (or $useExternal $useExisting) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  OPENAI_API_KEY: {{ default "" $secrets.openaiApiKey | quote }}

  KC_CLIENT_SECRET: {{ default "" $secrets.kcClientSecret | quote }}

  RABBITMQ_DEFAULT_PASS: {{ default "" $secrets.rabbitmqPassword | quote }}

  POSTGRES_PASSWORD: {{ default "" $secrets.postgresPassword | quote }}
{{- end }}
