
{{- if .Values.secrets.useExternal }}
---
# PostgreSQL Secrets ONLY
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-postgres-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: vault-team1
  target:
    name: {{ .Release.Name }}-postgres-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: team1/postgres
        property: POSTGRES_PASSWORD

---
# RabbitMQ Secrets ONLY
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-rabbitmq-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: vault-team1
  target:
    name: {{ .Release.Name }}-rabbitmq-secrets
    creationPolicy: Owner
  data:
    - secretKey: RABBITMQ_DEFAULT_USER
      remoteRef:
        key: team1/rabbitmq
        property: RABBITMQ_DEFAULT_USER
    - secretKey: RABBITMQ_DEFAULT_PASS
      remoteRef:
        key: team1/rabbitmq
        property: RABBITMQ_DEFAULT_PASS

---
# Core API Secrets (needs OpenAI, Postgres connection, RabbitMQ connection)
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-core-api-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: vault-team1
  target:
    name: {{ .Release.Name }}-core-api-secrets
    creationPolicy: Owner
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: team1/shared
        property: OPENAI_API_KEY
    - secretKey: OPENAI_API_BASE
      remoteRef:
        key: team1/shared
        property: OPENAI_API_BASE
    - secretKey: OPENAI_MODEL_NAME
      remoteRef:
        key: team1/shared
        property: OPENAI_MODEL_NAME
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: team1/postgres
        property: POSTGRES_PASSWORD
    - secretKey: RABBITMQ_DEFAULT_PASS
      remoteRef:
        key: team1/rabbitmq
        property: RABBITMQ_DEFAULT_PASS

---
# Workers Secrets (needs OpenAI, RabbitMQ)
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-workers-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: vault-team1
  target:
    name: {{ .Release.Name }}-workers-secrets
    creationPolicy: Owner
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: team1/shared
        property: OPENAI_API_KEY
    - secretKey: OPENAI_API_BASE
      remoteRef:
        key: team1/shared
        property: OPENAI_API_BASE
    - secretKey: OPENAI_MODEL_NAME
      remoteRef:
        key: team1/shared
        property: OPENAI_MODEL_NAME
    - secretKey: RABBITMQ_DEFAULT_PASS
      remoteRef:
        key: team1/rabbitmq
        property: RABBITMQ_DEFAULT_PASS

{{- end }}