{{- $secrets := .Values.secrets | default (dict) -}}
{{- $useExternal := and (hasKey $secrets "useExternal") $secrets.useExternal -}}

{{- if $useExternal }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Release.Name }}-vault-store
spec:
  provider:
    vault:
      server: "https://vault.kubepractice.ru"
      path: "kv"       # mount KV в Vault, если у вас другой — поправь
      version: "v2"

      auth:
        userPass:
          path: "userpass"
          username: {{ .Values.secrets.vault.username | default "" | quote }}
          password:
            secretRef:
              name: vault-credentials
              key: password


---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: {{ .Release.Name }}-vault-store

  target:
    name: {{ .Release.Name }}-secrets
    creationPolicy: Owner
    deletionPolicy: Retain

  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: {{ .Values.secrets.vault.path | default "team1/hr-assist" }}
        property: OPENAI_API_KEY

    - secretKey: KL_CLIENT_SECRET
      remoteRef:
        key: {{ .Values.secrets.vault.path | default "team1/hr-assist" }}
        property: KL_CLIENT_SECRET

    - secretKey: RABBITMQ_DEFAULT_PASS
      remoteRef:
        key: {{ .Values.secrets.vault.path | default "team1/hr-assist" }}
        property: RABBITMQ_DEFAULT_PASS

    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.vault.path | default "team1/hr-assist" }}
        property: POSTGRES_PASSWORD
        
    - secretKey: HTTP_PROXY
      remoteRef:
        key: {{ .Values.secrets.vault.path | default "team1/hr-assist" }}
        property: SQUID_PROXY_URL

    - secretKey: HTTPS_PROXY
      remoteRef:
        key: {{ .Values.secrets.vault.path | default "team1/hr-assist" }}
        property: SQUID_PROXY_URL

    - secretKey: NO_PROXY
      remoteRef:
        key: {{ .Values.secrets.vault.path | default "team1/hr-assist" }}
        property: NO_PROXY
{{- end }}
