apiVersion: v2
name: team1-hr-assist
description: HR Assist microservices (core_api + workers + frontend)
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: core-api
    version: 0.1.0
    repository: "file://./charts/core-api"
  - name: frontend
    version: 0.1.0
    repository: "file://./charts/frontend"
  - name: job-description-service
    version: 0.1.0
    repository: "file://./charts/job-description-service"
  - name: question-generation-service
    version: 0.1.0
    repository: "file://./charts/question-generation-service"
  - name: resume-evaluation-service
    version: 0.1.0
    repository: "file://./charts/resume-evaluation-service"
  - name: postgres
    version: 0.1.0
    repository: "file://./charts/postgres"
  - name: rabbitmq
    version: 0.1.0
    repository: "file://./charts/rabbitmq"